### ISSUE TITLE
Support for multiple_matches_per_ray_min_distance in Matching Python

### ISSUE THREAD

**Issue by paugier** [turbulencelyon/4d-ptv#5]
I quote @ddumont-2607 

> It remains a difference with the C++ code: in the Python code there is no parameter to set the minimum distance between two matches with the same ray. We noted that without such a parameter, wrong matches were found. Could you add this parameter in the Python code? It should correspond to the parameter multiplematchesperraymindistance of the C++ code. Thanks a lot!

See https://github.com/turbulencelyon/4d-ptv/search?q=multiplematchesperraymindistance

In the Python code, I think the associated condition has to be implemented in the function `make_approved_matches` (https://github.com/turbulencelyon/4d-ptv/blob/master/Matching/STMPython/stm_util.py#L529).

Of course, in Python we would use a variable `multiple_matches_per_ray_min_distance` (or simply `min_distance_matches_1ray`?) for readability.

Good news: the function `make_approved_matches` is not computationally intensive (~1% of the total time, still in pure Python) so adding this should not change too much the overall performance.

**Comment by jsalort** [comment]
That looks good !
