### ISSUE TITLE
Matching parallel

### ISSUE THREAD

**Issue by csavaro** [turbulencelyon/4d-ptv#9]
The function ParallelJobsMatching.m mentioned in the doc "11.3. Matching" is not in the repository.

And related to the parallelization of matching, the matching algorithms with for example the file "rays_0501-1000.dat" save results beginning with frame 1 instead of 501. This is an issue for the stitching that use the frame number.

**Comment by ddumont-2607** [comment]
Indeed, the function ```ParallelJobsMatching.m``` was missing. I added it at the right place.

The second point is not an issue as the reading function for the matches takes that into account that. That's why there is an argument minFrame for the function ```h52matches.m``` and in various processing functions.
